### ISSUE TITLE
None url with quality 320kps

### ISSUE THREAD

**Issue by Vipdt5k49** [thedtvn/zingmp3py#1]
I got None url with quality 320kps. It seems "sig" hashed from key is only for guest. we need key from logged in main.min.js.

**Comment by thedtvn** [comment]
> I got None url with quality 320kps. It seems "sig" hashed from key is only for guest. we need key from logged in main.min.js.

@Vipdt5k49  can  you  send me link  of  that  song ?

**Comment by thedtvn** [comment]
@Vipdt5k49 and  sory  that is  this  you  need  to check is a premium  audio or not by  user  `isVIP` var 
I will add account login  if  you  like to get premium audio when  you have VIP account

**Comment by Vipdt5k49** [comment]
below is my test:

In:
from zingmp3py import ZingMp3
zi = ZingMp3()

t=zi.getSongStreaming("ZWDB08FB")

for i in t:
    print(f'{i.quality}:{i.url}')

Out:
https://zingmp3.vn/api/v2/song/get/streaming?id=ZWDB08FB&apiKey=X5BM3w8N7MKozC0B85o4KMlzLZKhV00y&ctime=1687706639&sig=b29f2c7dac045f00fad45e94889f02b2ba41580d6a6016f14954bf78e511e8e278945ca21fdc679a4127c13bbac352af14af2a029e98d32fb9a462e2c31bea5a
128:https://mp3-s1-zmp3.zmdcdn.me/f458134d260ecf50961f/9178100986447968401?authen=exp=1687879440~acl=/f458134d260ecf50961f/*~hmac=5ba1f64937ca2d86cb0c7466169d82f1&fs=MTY4NzmUsICwNjY0MDE0MXx3ZWJWNnwwfDIwMy4yMTAdUngMTI5Ljk4
320:None

**Comment by thedtvn** [comment]
@Vipdt5k49 ye  that  song req login for 320 audio
![image](https://github.com/thedtvn/zingmp3py/assets/80153297/646f1394-a092-4267-8562-9ab3e12bfbec)

**Comment by thedtvn** [comment]
or  you  can use youtube_dl for this youtube_dl  support zingmp3 but  this is faster and have async

**Comment by Vipdt5k49** [comment]
> or  you  can use youtube_dl for this youtube_dl  support zingmp3 but  this is faster and have async
> 

Could you send me youtube_dl ?

**Comment by Vipdt5k49** [comment]
M thấy nó nâng cấp main.min.js lên ver 1.9.43 rồi, code b dùng ver 1.7.34 nên s_key khác s_key khi duyệt web, nhưng request vẫn ok nếu parameter ko có ver

**Comment by thedtvn** [comment]
> M thấy nó nâng cấp main.min.js lên ver 1.9.43 rồi, code b dùng ver 1.7.34 nên s_key khác s_key khi duyệt web, nhưng request vẫn ok nếu parameter ko có ver

các phiên bản không có gì khác nhău cả 
do mình vẫn dùng project này

**Comment by thedtvn** [comment]
mình sẽ update nó

**Comment by thedtvn** [comment]
> > or  you  can use youtube_dl for this youtube_dl  support zingmp3 but  this is faster and have async
> > 
> 
> Could you send me youtube_dl ?

@Vipdt5k49 go to google

**Comment by Vipdt5k49** [comment]
M sửa requestZing lấy cookies VIP export bằng tay thì get dc 320 url rồi.
Phần đăng nhập giờ nó làm qua quét qr zalo nên sửa get_ck lấy cookies VIP có vẻ hơi lằng nhằng :D
Cám ơn project của b nhé

**Comment by thedtvn** [comment]
> M sửa requestZing lấy cookies VIP export bằng tay thì get dc 320 url rồi.
> Phần đăng nhập giờ nó làm qua quét qr zalo nên sửa get_ck lấy cookies VIP có vẻ hơi lằng nhằng :D
> Cám ơn project của b nhé

@Vipdt5k49 mình đã từng làm đến login rồi nó không phức tạp nhưng nó liên quan đến quá nhiều thứ

**Comment by thedtvn** [comment]
> M sửa requestZing lấy cookies VIP export bằng tay thì get dc 320 url rồi. Phần đăng nhập giờ nó làm qua quét qr zalo nên sửa get_ck lấy cookies VIP có vẻ hơi lằng nhằng :D Cám ơn project của b nhé

@Vipdt5k49 cảm  ơn bạn

**Comment by thedtvn** [comment]
@Vipdt5k49 mình đã add login rồi đấy :>
